export const translations = {
  EN: {
    "contact.success": "Message sent! I will get back to you soon.",
    "contact.error": "An error occurred. Please try again.",
    "footer.rights": "All rights reserved.",
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.contact": "Contact",
    // Hero
    "hero.greeting": "Hi, I'm",
    "hero.title": "Telecommunications Engineer & Full-Stack Developer",
    "hero.tagline":
      "Delivering innovative solutions in Full-Stack, Data Engineering, and AI across Europe, Latin America, and Canada.",
    "hero.cta": "View Projects",
    "hero.contact": "Contact Me",
    "hero.based": "Based in",
    "hero.location": "Cali, Colombia",
    // About
    "about.title": "About Me",
    "about.story.title": "My Story",
    "about.story.desc":
      "Telecommunications Engineer with strong experience in Full-Stack Development, Data Engineering, and Artificial Intelligence. Skilled in delivering innovative solutions through international projects across Europe, Latin America, and Canada. Adaptable, multicultural, and product-oriented with a solid background in agile methodologies.",
    "about.edu.msc": "MSc INSA Lyon",
    "about.edu.mscdesc": "Telecom Eng. 2018–2021",
    "about.edu.dcu": "Exchange DCU",
    "about.edu.dcudesc": "AI Major, 2019–2020",
    "about.edu.uga": "BSc UGA Grenoble",
    "about.edu.ugadesc": "Physical Measurements",
    "about.edu.langs": "4 Languages",
    "about.edu.langsdesc": "FR, EN, ES, IT/DE",
    "about.cta": "Contact Me",
    // Skills
    "skills.title": "My Skills",
    "skills.progdata": "Programming & Data",
    "skills.js": "JavaScript/TypeScript",
    "skills.python": "Python",
    "skills.javac": "Java/C",
    "skills.sql": "SQL/NoSQL",
    "skills.tf": "TensorFlow/PyTorch",
    "skills.webcloud": "Web, Cloud & Tools",
    "skills.htmlcss": "HTML5/CSS3/React/Angular/Vue",
    "skills.node": "Node.js/Nest.js",
    "skills.docker": "Docker/Kubernetes/CI-CD",
    "skills.aws": "AWS/Azure/GCP",
    "skills.git": "Git/GitHub/Jira/Trello",
    "skills.frameworks": "Frameworks & Tools",
    "skills.react": "React",
    "skills.angular": "Angular",
    "skills.vue": "Vue.js",
    "skills.nodejs": "Node.js",
    "skills.sql2": "SQL/NoSQL",
    "skills.docker2": "Docker",
    "skills.aws2": "AWS",
    "skills.git2": "Git",
    // Projects
    "projects.title": "Featured Projects",
    "projects.p1.title": "Offline Payment Solution",
    "projects.p1.stack": "Node.js, Raspberry Pi",
    "projects.p1.desc":
      "Robust payment system for areas with unreliable internet, built with Node.js and Raspberry Pi.",
    "projects.p1.stack1": "Node.js",
    "projects.p1.stack2": "Raspberry Pi",
    "projects.p2.title": "Interactive E-Learning Platform",
    "projects.p2.stack": "Angular, Nest.js, Firebase",
    "projects.p2.desc":
      "Modern e-learning platform using Angular, Nest.js, and Firebase for real-time, interactive education.",
    "projects.p2.stack1": "Angular",
    "projects.p2.stack2": "Nest.js",
    "projects.p2.stack3": "Firebase",
    "projects.p3.title": "Sales Analytics Dashboard",
    "projects.p3.stack": "Python, SQL, Tableau",
    "projects.p3.desc":
      "Data-driven dashboard for restaurant sales analysis, built with Python, SQL, and Tableau.",
    "projects.p3.stack1": "Python",
    "projects.p3.stack2": "SQL",
    "projects.p3.stack3": "Tableau",
    "projects.p4.title": "Real-Time Flight Mapping",
    "projects.p4.stack": "Vue.js, Node.js",
    "projects.p4.desc":
      "Live flight tracking interface using Vue.js and Node.js for real-time data visualization.",
    "projects.p4.stack1": "Vue.js",
    "projects.p4.stack2": "Node.js",
    "projects.github": "GitHub",
    // Contact
    "contact.title": "Contact",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send",
    "contact.connect": "Connect with me",
    "contact.linkedin": "LinkedIn",
    "contact.github": "GitHub",
    "contact.email2": "Email",
    "contact.invite":
      "Feel free to reach out for collaborations, project ideas, or just to say hi!",
  },
  FR: {
    "contact.success": "Message envoyé ! Je vous répondrai rapidement.",
    "contact.error": "Une erreur est survenue. Veuillez réessayer.",
    "footer.rights": "Tous droits réservés.",
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.skills": "Compétences",
    "nav.projects": "Projets",
    "nav.contact": "Contact",
    "hero.greeting": "Bonjour, je suis",
    "hero.title": "Ingénieur Télécom & Développeur Full-Stack",
    "hero.tagline":
      "Des solutions innovantes en Full-Stack, Data Engineering et IA en Europe, Amérique Latine et Canada.",
    "contact.invite":
      "N’hésitez pas à me contacter pour collaborer, proposer un projet ou simplement dire bonjour !",
    "hero.cta": "Voir les projets",
    "hero.contact": "Me contacter",
    "hero.based": "Basé à",
    "hero.location": "Cali, Colombie",
    "about.title": "À propos de moi",
    // (removed duplicate, only keep correct FR translation above)
    "about.story.title": "Mon parcours",
    "about.story.desc":
      "Ingénieur Télécom avec une forte expérience en développement Full-Stack, Data Engineering et Intelligence Artificielle. Expérience internationale en Europe, Amérique Latine et Canada. Adaptable, multiculturel et orienté produit, avec une solide expérience des méthodes agiles.",
    "about.edu.msc": "MSc INSA Lyon",
    "about.edu.mscdesc": "Ingénieur Télécom 2018–2021",
    "about.edu.dcu": "Échange DCU",
    "about.edu.dcudesc": "Spécialité IA, 2019–2020",
    "about.edu.uga": "Licence UGA Grenoble",
    "about.edu.ugadesc": "Mesures Physiques",
    "about.edu.langs": "4 Langues",
    "about.edu.langsdesc": "FR, EN, ES, IT/DE",
    "about.cta": "Me contacter",
    "skills.title": "Compétences",
    "skills.progdata": "Programmation & Données",
    "skills.js": "JavaScript/TypeScript",
    "skills.python": "Python",
    "skills.javac": "Java/C",
    "skills.sql": "SQL/NoSQL",
    "skills.tf": "TensorFlow/PyTorch",
    "skills.webcloud": "Web, Cloud & Outils",
    "skills.htmlcss": "HTML5/CSS3/React/Angular/Vue",
    "skills.node": "Node.js/Nest.js",
    "skills.docker": "Docker/Kubernetes/CI-CD",
    "skills.aws": "AWS/Azure/GCP",
    "skills.git": "Git/GitHub/Jira/Trello",
    "skills.frameworks": "Frameworks & Outils",
    "skills.react": "React",
    "skills.angular": "Angular",
    "skills.vue": "Vue.js",
    "skills.nodejs": "Node.js",
    "skills.sql2": "SQL/NoSQL",
    "skills.docker2": "Docker",
    "skills.aws2": "AWS",
    "skills.git2": "Git",
    "projects.title": "Projets phares",
    "projects.p1.title": "Solution de paiement hors-ligne",
    "projects.p1.stack": "Node.js, Raspberry Pi",
    "projects.p1.desc":
      "Système de paiement robuste pour zones sans internet, avec Node.js et Raspberry Pi.",
    "projects.p1.stack1": "Node.js",
    "projects.p1.stack2": "Raspberry Pi",
    "projects.p2.title": "Plateforme E-Learning interactive",
    "projects.p2.stack": "Angular, Nest.js, Firebase",
    "projects.p2.desc":
      "Plateforme e-learning moderne avec Angular, Nest.js et Firebase pour une éducation interactive en temps réel.",
    "projects.p2.stack1": "Angular",
    "projects.p2.stack2": "Nest.js",
    "projects.p2.stack3": "Firebase",
    "projects.p3.title": "Dashboard Analytics Ventes",
    "projects.p3.stack": "Python, SQL, Tableau",
    "projects.p3.desc":
      "Dashboard pour l’analyse des ventes restaurants, avec Python, SQL et Tableau.",
    "projects.p3.stack1": "Python",
    "projects.p3.stack2": "SQL",
    "projects.p3.stack3": "Tableau",
    "projects.p4.title": "Cartographie de vols en temps réel",
    "projects.p4.stack": "Vue.js, Node.js",
    "projects.p4.desc":
      "Interface de suivi de vols en direct avec Vue.js et Node.js.",
    "projects.p4.stack1": "Vue.js",
    "projects.p4.stack2": "Node.js",
    "projects.github": "GitHub",
    "contact.title": "Contact",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.subject": "Objet",
    "contact.message": "Message",
    "contact.send": "Envoyer",
    "contact.connect": "Me contacter",
    "contact.linkedin": "LinkedIn",
    "contact.github": "GitHub",
    "contact.email2": "Email",
  },
  ES: {
    "contact.success": "¡Mensaje enviado! Te responderé pronto.",
    "contact.error": "Ocurrió un error. Por favor, inténtalo de nuevo.",
    "footer.rights": "Todos los derechos reservados.",
    "nav.home": "Inicio",
    "nav.about": "Sobre mí",
    "nav.skills": "Habilidades",
    "nav.projects": "Proyectos",
    "nav.contact": "Contacto",
    "hero.greeting": "Hola, soy",
    "hero.title": "Ingeniero en Telecomunicaciones & Full-Stack",
    "hero.tagline":
      "Soluciones innovadoras en Full-Stack, Ingeniería de Datos e IA en Europa, Latinoamérica y Canadá.",
    "hero.cta": "Ver proyectos",
    "hero.contact": "Contáctame",
    "hero.based": "Basado en",
    "hero.location": "Cali, Colombia",
    "about.title": "Sobre mí",
    "about.story.title": "Mi historia",
    "about.story.desc":
      "Ingeniero en Telecomunicaciones con experiencia en Full-Stack, Ingeniería de Datos e Inteligencia Artificial. Proyectos internacionales en Europa, Latinoamérica y Canadá. Adaptable, multicultural y orientado a producto, con experiencia en metodologías ágiles.",
    "about.edu.msc": "MSc INSA Lyon",
    "about.edu.mscdesc": "Ing. Telecom 2018–2021",
    "about.edu.dcu": "Intercambio DCU",
    "about.edu.dcudesc": "Especialidad IA, 2019–2020",
    "about.edu.uga": "Licenciatura UGA Grenoble",
    "about.edu.ugadesc": "Mediciones Físicas",
    "about.edu.langs": "4 Idiomas",
    "about.edu.langsdesc": "FR, EN, ES, IT/DE",
    "about.cta": "Contáctame",
    "skills.title": "Habilidades",
    "skills.progdata": "Programación y Datos",
    "skills.js": "JavaScript/TypeScript",
    "skills.python": "Python",
    "skills.javac": "Java/C",
    "skills.sql": "SQL/NoSQL",
    "skills.tf": "TensorFlow/PyTorch",
    "skills.webcloud": "Web, Cloud y Herramientas",
    "skills.htmlcss": "HTML5/CSS3/React/Angular/Vue",
    "skills.node": "Node.js/Nest.js",
    "skills.docker": "Docker/Kubernetes/CI-CD",
    "skills.aws": "AWS/Azure/GCP",
    "skills.git": "Git/GitHub/Jira/Trello",
    "skills.frameworks": "Frameworks y Herramientas",
    "skills.react": "React",
    "skills.angular": "Angular",
    "skills.vue": "Vue.js",
    "skills.nodejs": "Node.js",
    "skills.sql2": "SQL/NoSQL",
    "skills.docker2": "Docker",
    "skills.aws2": "AWS",
    "skills.git2": "Git",
    "projects.title": "Proyectos destacados",
    "projects.p1.title": "Solución de pago offline",
    "projects.p1.stack": "Node.js, Raspberry Pi",
    "projects.p1.desc":
      "Sistema de pago robusto para zonas sin internet, con Node.js y Raspberry Pi.",
    "projects.p1.stack1": "Node.js",
    "projects.p1.stack2": "Raspberry Pi",
    "projects.p2.title": "Plataforma E-Learning interactiva",
    "projects.p2.stack": "Angular, Nest.js, Firebase",
    "projects.p2.desc":
      "Plataforma e-learning moderna con Angular, Nest.js y Firebase para educación interactiva en tiempo real.",
    "projects.p2.stack1": "Angular",
    "projects.p2.stack2": "Nest.js",
    "projects.p2.stack3": "Firebase",
    "projects.p3.title": "Dashboard de ventas",
    "projects.p3.stack": "Python, SQL, Tableau",
    "projects.p3.desc":
      "Dashboard para análisis de ventas en restaurantes, con Python, SQL y Tableau.",
    "projects.p3.stack1": "Python",
    "projects.p3.stack2": "SQL",
    "projects.p3.stack3": "Tableau",
    "projects.p4.title": "Mapa de vuelos en tiempo real",
    "projects.p4.stack": "Vue.js, Node.js",
    "projects.p4.desc":
      "Interfaz de seguimiento de vuelos en vivo con Vue.js y Node.js.",
    "projects.p4.stack1": "Vue.js",
    "projects.p4.stack2": "Node.js",
    "projects.github": "GitHub",
    "contact.title": "Contacto",
    "contact.name": "Nombre",
    "contact.email": "Correo",
    "contact.subject": "Asunto",
    "contact.message": "Mensaje",
    "contact.send": "Enviar",
    "contact.connect": "Conecta conmigo",
    "contact.invite":
      "No dudes en contactarme para colaborar, proponer un proyecto o simplemente saludarme!",
    "contact.linkedin": "LinkedIn",
    "contact.github": "GitHub",
    "contact.email2": "Correo",
  },
};
